# Generated by Django 4.2.3 on 2023-07-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('orderNumber', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('uploadFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'UploadFile',
            },
        ),
    ]
