# Generated by Django 4.2.3 on 2023-07-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_alter_uploadfile_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadFile',
            field=models.FileField(blank=True, null=True, upload_to='media/uploadedfiles/'),
        ),
    ]
