# Generated by Django 4.2.3 on 2023-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('orderDescription', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('contractor', models.CharField(max_length=254)),
                ('appointmentDate', models.DateField()),
                ('primaryContact', models.EmailField(max_length=254)),
                ('secondaryContact', models.EmailField(max_length=254)),
                ('notes', models.CharField(max_length=254, null=True)),
                ('dateLastUpdate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
