# Generated by Django 4.2.3 on 2023-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderNumber',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
