# Generated by Django 4.2.3 on 2023-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('orderNumber', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('readUnread', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
