# Generated by Django 4.2.3 on 2023-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='appointmentComplete',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='orders',
            name='phoneNumber',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
