# Generated by Django 4.2.3 on 2023-07-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0002_remove_orders_id_alter_orders_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
