# Generated by Django 4.2.3 on 2023-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0002_orders_appointmentcomplete_orders_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dateClosed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
