# Generated by Django 4.2.3 on 2023-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0004_alter_orders_appointmentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
