# Generated by Django 4.2.3 on 2023-07-06 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0005_alter_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dateLastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
