# Generated by Django 4.2.3 on 2023-07-06 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0006_alter_orders_datelastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='dateLastUpdate',
            field=models.DateTimeField(),
        ),
    ]
