# Generated by Django 4.2.3 on 2023-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0007_orders_datecreated_alter_orders_datelastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='appointmentDate',
            field=models.DateTimeField(null=True),
        ),
    ]
