# Generated by Django 4.2.3 on 2023-07-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0008_alter_orders_appointmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='appointmentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
