# Generated by Django 4.2.3 on 2023-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0009_alter_orders_appointmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
