# Generated by Django 4.2.3 on 2023-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0011_alter_orders_datelastupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('contractor', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('secondaryContact', models.EmailField(max_length=254)),
                ('services', models.CharField(blank=True, max_length=9999, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contractors',
            },
        ),
    ]
