# Generated by Django 4.2.3 on 2023-07-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0012_contractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractors',
            name='id_no',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='id_no',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal001.contractors'),
        ),
    ]
