# Generated by Django 4.2.3 on 2023-07-10 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal001', '0013_alter_orders_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='primaryContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
