# Generated by Django 4.2.3 on 2023-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0013_contractors_id_no_orders_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderClosed',
            field=models.BooleanField(default=None),
        ),
    ]
