# Generated by Django 4.2.3 on 2023-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0014_orders_orderclosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractors',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='orderClosed',
        ),
        migrations.AlterField(
            model_name='orders',
            name='contractor',
            field=models.CharField(max_length=254),
        ),
    ]
