# Generated by Django 4.2.3 on 2023-07-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0015_alter_contractors_secondarycontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='portal001.contractors'),
        ),
    ]
