# Generated by Django 4.2.3 on 2023-07-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0016_contractors_id_no_orders_id_no_orders_orderclosed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderClosed',
        ),
    ]
