# Generated by Django 4.2.3 on 2023-07-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0017_remove_orders_orderclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderClosed',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
