# Generated by Django 4.2.3 on 2023-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal001', '0018_alter_contractors_secondarycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractors',
            name='secondaryContact',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
